### PR TITLE
Fix Safari Styling Issues

### LINKED ISSUE #483: Fix Safari Plan Styling
image

The plan styling is broken right now in Safari (only one year displays, and takes up the entire screen vertically, show buttons are in the wrong place).

### PR DESCRIPTION
**Pull request by AlpacaFur**
# Description

Fixes styling in Safari and brings the styling more in-line with the current styling plans on Figma.

Styling in Safari with this PR:
Image of the newly fixed page in Safari

Closes #483 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I manually checked to see if it looks right and drag-and-drop still works properly in Safari, Firefox, and Microsoft Edge (chromium).

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/frontend-v2/components/Plan/ScheduleYear.tsx [hunk 1]
```diff
@@ -68,7 +60,7 @@ export const ScheduleYear: React.FC<ScheduleYearProps> = ({
   }, 0);
 
   return (
-    <Flex flexDirection="column" height="100%" minHeight="inherit">
```
Comment (AlpacaFur) [inline packages/frontend-v2/components/Plan/ScheduleYear.tsx:71]: Most of the issue seemed to be a difference with how Safari handles `height:100%` and minHeight, so I went through and replaced that with some flexbox styling.

**Review by aryanshah701 — APPROVED** [review]
looks good to me! thank you so so much! <3
